name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt install -y libmhash-dev libmcrypt-dev libjpeg62-dev zlib1g-dev build-essential cmake
    - name: setup cmake
      run: mkdir build && cd build && cmake ..
    - name: compile project
      run: make -j2
    - name: Run unit tests
      run: make test
    - name: Run cracker tests
      run: cd ../tests/stegseek && ./testCracker.sh && cd ../..
    - name: Create a .deb package
      run: bash package/package.sh
    - name: Save the .deb as a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: stegseek-deb-package
        path: stegseek*.deb
